booktime/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.views.generic import TemplateView, DetailView
from main import views, models


urlpatterns = [
    path(
        "product/<slug:slug>/",
        DetailView.as_view(model=models.Product,
                           template_name="product_detail.html"),
        name="product",
    ),
    path(
        "products/<slug:tag>/",
        views.ProductListView.as_view(),
        name="product",
    ),
    # path(
    #     "products/",
    #     views.ProductListView.as_view(),
    #     name="products",
    # ),
    path(
        "about-us/",
        TemplateView.as_view(template_name="about_us.html"),
        name="about_us"
    ),
    path(
        "",
        TemplateView.as_view(template_name="home.html"),
        name="home"
    ),
    path(
        "contact-us/",
        views.ContactUsView.as_view(),
        name="contact_us",
    ),
]

urls.py
from django.urls import path
from django.views.generic import TemplateView
import views

urlpatterns = [
    path(
        "about-us/",
        TemplateView.as_view(template_name="about_us.html"),
        name="about_us"
    ),
    path(
        "",
        TemplateView.as_view(template_name="home.html"),
        name="home"
    ),
    path(
        "contact-us/",
        views.ContactUsView.as_view(),
        name="contact_us",
    ),
]

main/models.py
from django.db import models

# Create your models here.


class ActiveManager(models.Manager):
    def active(self):
        return self.filter(active=True)


class ProductTag(models.Model):
    name = models.CharField(max_length=32)
    slug = models.SlugField(max_length=48)
    description = models.TextField(blank=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    def natural_key(self):
        return (self.slug,)


class Product(models.Model):
    name = models.CharField(max_length=32)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    slug = models.SlugField(max_length=48)
    active = models.BooleanField(default=True)
    in_stock = models.BooleanField(default=True)
    date_updated = models.DateTimeField(auto_now=True)
    objects = ActiveManager()
    tags = models.ManyToManyField(ProductTag, blank=True)

    def __str__(self):
        return self.name


class ProductImage(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE
    )
    image = models.ImageField(upload_to="product-images")
    thumbnail = models.ImageField(
        upload_to="product-thumbnails", null=True
    )

    def __str__(self):
        return self.product.name + " Image"

main/forms.py
from django import forms
from django.core.mail import send_mail
import logging
logger = logging.getLogger(__name__)


class ContactForm(forms.Form):
    name = forms.CharField(label='Your name', max_length=100)
    message = forms.CharField(
        label='Your Message',
        max_length=600, widget=forms.Textarea
    )

    def send_mail(self):
        logger.info("Sending email to customer service")
        message = "From: {0}\n{1}".format(
            self.cleaned_data["name"],
            self.cleaned_data["message"],
        )
        send_mail(
            "Site message",
            message,
            "site@booktime.domain",
            ["customerservice@booktime.domain"],
            fail_silently=False,
        )

main/views.py
from main import models, forms
from django.shortcuts import get_object_or_404
from django.views.generic.edit import FormView
from django.views.generic.list import ListView


class ContactUsView(FormView):
    template_name = "contact_form.html"
    form_class = forms.ContactForm
    success_url = "/"

    # def contact_us(self, request):
    #     if request.method == 'POST':
    #         form = forms.ContactForm(request.POST)
    #     if form.is_valid():
    #         form.send_mail()
    #         return HttpResponseRedirect('/')
    #     else:
    #         form = forms.ContactForm()
    #     return render(request, 'contact_form.html', {'form': form})

    def form_valid(self, form):
        form.send_mail()
        return super().form_valid(form)


class ProductListView(ListView):
    template_name = "product_list.html"
    paginate_by = 4

    def get_queryset(self):
        tag = self.kwargs['tag']
        self.tag = None
        if tag != "all":
            self.tag = get_object_or_404(
                models.ProductTag, slug=tag
            )
        if self.tag:
            products = models.Product.objects.active().filter(
                tags=self.tag
            )
        else:
            products = models.Product.objects.active()
        return products.order_by("name")

main/templates/about_us.html
{% extends "base.html" %}
{% block content %}
<h2>About us</h2>
<p>BookTime is a company that sells books online.</p>
{% endblock content %}

main/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-tofit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/
css/bootstrap.min.css">
    <title>BookTime</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">BookTime</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item {% if request.path == '/' %} active {% endif %}">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item {% if request.path == '/about-us/' %} active {% endif %}">
                    <a class="nav-link" href="/about-us/">About us</a>
                </li>
                <li class="nav-item {% if request.path == '/contact-us/' %} active {% endif %}">
                    <a class="nav-link" href="/contact-us/">Contact Us</a>
                </li>
                <li class="nav-item {% if request.path == '/products/all/' %} active {% endif %}">
                    <a class="nav-link" href="/products/all/">Products</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/
1.12.9/umd/popper.min.js">
</script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/
bootstrap.min.js">
</script>
</body>

</html>

main/templates/contact_form.html
{% extends "base.html" %}
{% block content %}
<h2>Contact us</h2>
<p>Please fill the form below to contact us</p>
<form method="POST">
    {% csrf_token %}
    <div class="form-group">
        {{ form.name.label_tag }}
        <input type="text" class="form-control {% if form.name.errors %} is-invalid {% endif %}" id="id_name"
            name="name" placeholder="Your name" value="{{ form.name.value|default:'' }}">
        {% if form.name.errors %}
        <div class="invalid-feedback">
            {{ form.name.errors }}
        </div>
        {% endif %}
    </div>
    <div class="form-group">
        {{ form.message.label_tag }}
        <textarea class="form-control {% if form.message.errors %}
        is-invalid {% endif %}" id="id_message" name="message" rows="3">
        {{ form.message.value|default:""}}
        </textarea>
        {% if form.message.errors %}
        <div class="invalid-feedback">
            {{ form.message.errors }}
        </div>
        {% endif %}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock content %}

main/templates/home.html
{% extends "base.html" %}
{% block content %}
<h2>Booktime</h2>
<p>this will be the content of home</p>
{% endblock content %}

main/templates/product_detail.html
{% extends "base.html" %}
{% block content %}
<h1>products</h1>
<table class="table">
    <tr>
        <th>Name</th>
        <td>{{ object.name }}</td>
    </tr>
    <tr>
        <th>Cover images</th>
        <td>
            {% for image in object.productimage_set.all %}
            <img src="{{ image.image.url }}" alt="cover" />
            {% endfor %}
        </td>
    </tr>
    <tr>
        <th>Price</th>
        <td>{{ object.price }}</td>
    </tr>
    <tr>
        <th>Description</th>
        <td>{{ object.description|linebreaks }}</td>
    </tr>
    <tr>
        <th>Tags</th>
        <td>{{ object.tags.all|join:","|default:"No tags
available" }}</td>
    </tr>
    <tr>
        <th>In stock</th>
        <td>{{ object.in_stock|yesno|capfirst }}</td>
    </tr>
    <tr>
        <th>Updated</th>
        <td>{{ object.date_updated|date:"F Y" }}</td>
    </tr>
</table>
<a href="{% url "add_to_basket" %}?product_id={{ object.id }}">
    Add to basket</a>
{% endblock content %}

main/templates/product_list.html
{% extends "base.html" %}
{% block content %}
<h1>products</h1>
{% for product in page_obj %}
<p>{{ product.name }}</p>
<p>
    <a href="{% url "product" product.slug %}">See it here</a>
</p>
{% if not forloop.last %}
<hr>
{% endif %}
{% endfor %}
<nav>
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{page_obj.previous_page_number}}">
                Previous</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#">Previous</a>
        </li>
        {% endif %}
        {% for pagenum in page_obj.paginator.page_range %}
        <li class="page-item{% if page_obj.number == pagenum %}
active{% endif %}">
            <a class="page-link" href="?page={{pagenum}}">{{pagenum}}
            </a>
        </li>
        {% endfor %}
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{page_obj.next_
page_number}}">Next</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#">Next</a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endblock content %}